meta_product_name: "Findway"
meta_title: "Findway - La crème du coaching"
meta_description: "Trouver un coach d'orientation, rapidement, simplement"
meta_image: "metaimage.png" # should exist in `app/assets/images/`
